//
//  AccentButtonStyle.swift
//  Split Happens
//
//  Auto-generated by AI on 7/19/25.
//

import SwiftUI

/// A pill-shaped button style filled with the app accent colour.
/// Automatically dims and scales when pressed.
struct AccentButtonStyle: ButtonStyle {
    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .font(AppFonts.bodyLarge)
            .foregroundColor(AppColors.primaryText)
            .padding(.horizontal, 20)
            .padding(.vertical, 14)
            .background(AppColors.accent)
            .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))
            .scaleEffect(configuration.isPressed ? 0.97 : 1)
            .opacity(configuration.isPressed ? 0.9 : 1)
    }
}

extension Button {
    /// Applies `AccentButtonStyle`.
    func accentButtonStyle() -> some View {
        self.buttonStyle(AccentButtonStyle())
    }
} 