//
//  CardView.swift
//  Split Happens
//
//  Auto-generated by AI on 7/19/25.
//

import SwiftUI

/// A convenience container that applies the app's card style and spacing.
struct CardView<Content: View>: View {
    let content: Content
    
    init(@ViewBuilder content: () -> Content) {
        self.content = content()
    }
    
    var body: some View {
        content
            .padding()
            .background(AppColors.cardBackground)
            .elegantCard()
    }
} 