//
//  GradientBackground.swift
//  Split Happens
//
//  Auto-generated by AI on 7/19/25.
//

import SwiftUI

/// Abstract blurred gradient circles reminiscent of the reference design.
/// Place this view *behind* content (e.g. in a `ZStack`) to get organic blobs.
struct GradientBackground: View {
    var body: some View {
        GeometryReader { proxy in
            let size = proxy.size
            ZStack {
                Circle()
                    .fill(LinearGradient(colors: [AppColors.accent, AppColors.accentSecondary], startPoint: .topLeading, endPoint: .bottomTrailing))
                    .frame(width: size.width * 0.8)
                    .position(x: size.width * 0.8, y: size.height * -0.1)
                    .blur(radius: 120)
                    .opacity(0.55)
                
                Circle()
                    .fill(LinearGradient(colors: [Color.purple, Color.indigo], startPoint: .top, endPoint: .bottom))
                    .frame(width: size.width * 0.6)
                    .position(x: size.width * 0.1, y: size.height * 0.9)
                    .blur(radius: 120)
                    .opacity(0.45)
            }
            .ignoresSafeArea()
        }
    }
} 