//
//  IconCircleButton.swift
//  Split Happens
//
//  Auto-generated by AI on 7/19/25.
//

import SwiftUI

/// A floating circular button with an SF Symbol icon.
struct IconCircleButton: View {
    let systemName: String
    let size: CGFloat
    let action: () -> Void
    
    init(_ systemName: String, size: CGFloat = 20, action: @escaping () -> Void) {
        self.systemName = systemName
        self.size = size
        self.action = action
    }
    
    var body: some View {
        Button(action: action) {
            Image(systemName: systemName)
                .font(.system(size: size, weight: .bold))
                .foregroundColor(AppColors.primaryText)
                .frame(width: size * 2, height: size * 2)
                .background(AppColors.accent)
                .clipShape(Circle())
                .shadow(color: AppColors.accent.opacity(0.4), radius: 10, x: 0, y: 4)
        }
        .buttonStyle(.plain)
    }
} 