//
//  LargeStatTile.swift
//  Split Happens
//
//  Auto-generated by AI on 7/19/25.
//

import SwiftUI

struct LargeStatTile: View {
    let title: String
    let value: String
    let foreground: Color
    
    init(title: String, value: String, foreground: Color = AppColors.primaryText) {
        self.title = title
        self.value = value
        self.foreground = foreground
    }
    
    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(title)
                .font(AppFonts.caption)
                .foregroundColor(AppColors.secondaryText)
            Text(value)
                .font(AppFonts.title2)
                .foregroundColor(foreground)
        }
        .padding()
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(AppColors.cardBackground)
        .elegantCard()
    }
} 