//
//  Typography.swift
//  Split Happens
//
//  Auto-generated by AI on 7/19/25.
//

import SwiftUI

/// Central place to access the app's typography tokens.
/// All fonts use Apple's rounded design for a friendly fintech feel.
struct AppFonts {
    // MARK: - Display / Titles
    static let largeTitle      = Font.system(size: 34, weight: .bold, design: .rounded)
    static let title           = Font.system(size: 28, weight: .bold, design: .rounded)
    static let title2          = Font.system(size: 22, weight: .semibold, design: .rounded)
    static let title3          = Font.system(size: 20, weight: .semibold, design: .rounded)
    
    // MARK: - Body
    static let bodyLarge       = Font.system(size: 17, weight: .regular, design: .rounded)
    static let body            = Font.system(size: 15, weight: .regular, design: .rounded)
    static let caption         = Font.system(size: 12, weight: .regular, design: .rounded)
    
    // Convenience custom font builder if needed elsewhere
    static func rounded(size: CGFloat, weight: Font.Weight = .regular) -> Font {
        Font.system(size: size, weight: weight, design: .rounded)
    }
}

// MARK: - View Helpers
extension View {
    /// Applies the primary accent color to text.
    func accentText() -> some View {
        self.foregroundColor(AppColors.accent)
    }
    /// Applies primary text color.
    func primaryText() -> some View {
        self.foregroundColor(AppColors.primaryText)
    }
} 